version: "3"
services:
  proxy:
    image: linuxserver/swag
    container_name: zero-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # TODO: Edit
      - URL=ayanami.dev
      - SUBDOMAINS=i,ii,iii,iv,v
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - $PWD/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  # Nodes
  node:
    image: playzero/subzero:latest
    container_name: node
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "ZERO-AYANAMI-i",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
      ]
  node2:
    image: playzero/subzero:latest
    container_name: node2
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node2:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "ZERO-AYANAMI-ii",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
      ]
  node3:
    image: playzero/subzero:latest
    container_name: node3
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node3:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "ZERO-AYANAMI-iii",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
      ]
  node4:
    image: playzero/subzero:latest
    container_name: node4
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node4:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "ZERO-AYANAMI-iv",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
      ]
  node5:
    image: playzero/subzero:latest
    container_name: node5
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node5:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "ZERO-AYANAMI-v",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
      ]