version: "3"
services:
  proxy:
    image: linuxserver/swag
    container_name: zero-proxy
    env_file:
      - $PWD/config/letsencrypt-env
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/config/node.subdomain.conf:/config/nginx/proxy-confs/node.subdomain.conf
      - proxyVolume:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  node:
    image: playzero/subzero
    container_name: zero-node
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/keys/:/data/chains/zero-alphaville/keystore/
    depends_on:
      - proxy
    command:
      [
        "/usr/local/bin/subzero",
        "--base-path",
        "/data",
        "--name",
        "${NAME}",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
      ]

  ipfs-node:
    image: lactore/zero-ipfs-node
    container_name: zero-ipfs
    restart: unless-stopped
    volumes: ipfsData:/data/ipfs

volumes:
  proxyVolume:
  ipfsData:
