version: "3"
services:
  proxy:
    image: linuxserver/swag
    container_name: zero-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # TODO: Edit
      - URL=ayanami.dev
      - SUBDOMAINS=I,II
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - $PWD/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  # Nodes
  node:
    image: playzero/subzero
    container_name: node
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "I",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
        "--bootnodes",
        "/dns/alphaville-0.zero.io/tcp/30333/p2p/12D3KooWPPkXsaSBtGyuYLcQthJkN7DRAmaNkN38FTZeoMX2kLgh",
        "/dns/alphaville-0.zero.io/tcp/9944/ws/p2p/12D3KooWPPkXsaSBtGyuYLcQthJkN7DRAmaNkN38FTZeoMX2kLgh",
        "/dns/alphaville-1.zero.io/tcp/30333/p2p/12D3KooWSJb1iJ5rJdgNzVBasxLhC27BX9fNkNith55ivuqUojNf",
        "/dns/alphaville-1.zero.io/tcp/9944/ws/p2p/12D3KooWSJb1iJ5rJdgNzVBasxLhC27BX9fNkNith55ivuqUojNf",
      ]
  node2:
    image: playzero/subzero
    container_name: node2
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - $PWD/date-node2:/data
    depends_on:
      - proxy
    command: [
        "/usr/local/bin/subzero",
        # TODO: Add name
        "--name",
        "II",
        "--validator",
        "--ws-external",
        "--rpc-external",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--public-addr",
        "/ip4/0.0.0.0",
        "--telemetry-url",
        "wss://telemetry.polkadot.io/submit/ 5",
        "--bootnodes",
        "/dns/alphaville-0.zero.io/tcp/30333/p2p/12D3KooWPPkXsaSBtGyuYLcQthJkN7DRAmaNkN38FTZeoMX2kLgh",
        "/dns/alphaville-0.zero.io/tcp/9944/ws/p2p/12D3KooWPPkXsaSBtGyuYLcQthJkN7DRAmaNkN38FTZeoMX2kLgh",
        "/dns/alphaville-1.zero.io/tcp/30333/p2p/12D3KooWSJb1iJ5rJdgNzVBasxLhC27BX9fNkNith55ivuqUojNf",
        "/dns/alphaville-1.zero.io/tcp/9944/ws/p2p/12D3KooWSJb1iJ5rJdgNzVBasxLhC27BX9fNkNith55ivuqUojNf",
      ]
